### ISSUE TITLE
By-Hash Folders

### ISSUE THREAD

**Issue by JakeyPrime** [Stifler6996/apt-mirror#10]
Downloaded 18.04 and 20.04 mirrors and seems I have everything I need, however when pointing a local or even remote server to my mirror, by-hash folders are missing.

Likely user error but I can't seem to find any up to date information on fixing it.

Cheers!

![](https://hep.gg/DGenRmO3p)

**Comment by Stifler6996** [comment]
Can you show me your config please.
Are you trying to mirror "deb-src" in it anywhere?

**Comment by JakeyPrime** [comment]
> Can you show me your config please. Are you trying to mirror "deb-src" in it anywhere?

I am mirroring deb-src for 20, 18, and now 16, I changed nothing in the config and suddenly, it's just working.

I have a feeling for anyone who is as confused as I was, a stubborn version of the old apt-mirror was hanging out, ensure you're launching it directly after replacing or symlinking. For some reason the old version was still working and doesn't crab cnf or hash files like yours does.

Super strange, appreciate the help anyways.

**Comment by Stifler6996** [comment]
Please be aware of  [#6](https://github.com/Stifler6996/apt-mirror/issues/6)
Most people never need deb-src (this is not the same as -dev packages).

Some packages in the deb-src do not contain the older MD5, and only contain SHA1 (or better). In these cases, you will come into errors with deb-src trying to mirror those.

I am aware of this, again refer #6.

Thanks for the report.
