### ISSUE TITLE
Raspbian Repo Setup

### ISSUE THREAD

**Issue by JakeyPrime** [Stifler6996/apt-mirror#11]
Me again,

Looking to setup raspbian with apt-mirror rather than their own tool that is incredibly slow (talking 5 days in at this point) after downloading 1.4tb of other mirrors with apt-mirror in a few hours. Tried with the documented ways and faced connection refused from their mirrors, likely a me issue and with their poor documentation on getting a mirror running

This isn't an issue with the project obviously, and purely with my brain and familiarity with pulling "nonstandard" architecture.

Any help in getting this added and mirroring at literally 200 times the speed would be appreciated, haha.

Thanks!

**Comment by Stifler6996** [comment]
`deb-armhf http://raspbian.raspberrypi.org/raspbian bullseye main firmware contrib non-free rpi`

as for arm64, you can get raspian bullseye by adding this line:
`deb-arm64 http://archive.raspberrypi.org/debian bullseye main`
You will note that you cannot get firmware, rpi, non-free etc from this repository. I don't understand their philosophy for this.

As an example: I tried to mirror from my local raspberry repo, and you'll notice they file things in different places. but its there.
If you want to mirror a local repo, you might need to find the right starting places for the respositories (crazy).

`deb-armhf http://mirror.aarnet.edu.au/pub/raspbian/raspbian bullseye main firmware contrib non-free rpi`
`deb-arm64 http://mirror.aarnet.edu.au/pub/raspbian/multiarch bullseye main`
