### ISSUE TITLE
Unable to mirror https://packages.sury.org/php

### ISSUE THREAD

**Issue by foss4ever** [Stifler6996/apt-mirror#12]
For some reason, I'm unable to mirror the repo https://packages.sury.org/php

When I add that repo to my mirror.list like so:
deb https://packages.sury.org/php bullseye main

I get this when running apt-mirror:

![billede](https://user-images.githubusercontent.com/72194332/155100371-5ab1bbd6-7996-4495-8cc9-513126195c7f.png)

What might be the issue here?

Using that exact same repo directly on a client's sources.list works just fine:

![billede](https://user-images.githubusercontent.com/72194332/155108927-5ac51ffc-39db-40a2-894c-76ff858c660a.png)

**Comment by Stifler6996** [comment]
This mirror is not mirror-able. It is missing major components such as "Contents-amd64.gz" (and any other relevant ones)

This is an example of a mirrorable repo.
![image](https://user-images.githubusercontent.com/12870096/155450770-c00e579a-0c22-4360-bff3-8ca10551b364.png)

**Comment by chutzimir** [comment]
@foss4ever  This may have been fixed with #21 - it seems to mirror just fine now.
