### ISSUE TITLE
apt-mirror: can't copy .. . apt-mirror line 929

### ISSUE THREAD

**Issue by vetalsmith** [Stifler6996/apt-mirror#32]
apt-mirror: can't copy /media/ubuntu-repo/22.04/skel/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz to /media/ubuntu-repo/22.04/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz at /usr/bin/apt-mirror line 929.

**Comment by chutzimir** [comment]
@vetalsmith Can you try the following commands by hand and give us the output? As @Stifler6996 mentioned, it must be a permission issue.

```
stat --terse /media/ubuntu-repo/22.04/skel/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz to /media/ubuntu-repo/22.04/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz /media/ubuntu-repo/22.04/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates

ln --verbose /media/ubuntu-repo/22.04/skel/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz to /media/ubuntu-repo/22.04/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz

cp --verbose --archive /media/ubuntu-repo/22.04/skel/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz to /media/ubuntu-repo/22.04/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/Contents-i386.gz 
```

**Comment by Stifler6996** [comment]
Okay, we'll put it down to your hardware failure for now. If/when you get back running and its a problem again test with the above steps. We can reopen if necessary.
