### ISSUE TITLE
apt-mirror: can't open index download.docker.com/linux/ubuntu//dists/jammy/stable/binary-arm64/Packages in process_index at /usr/bin/apt-mirror line 932.

### ISSUE THREAD

**Issue by Roger53** [Stifler6996/apt-mirror#45]
Hi Stifler
(no idea why parts of the issue are larger fonts, not my intention )

After removing ( by a script, not manually anymore :-) )  the tabs and double spaces, your tool has been performing perfectly, Thanks

Now migrating to debian-bullseye and Ubuntu-jammy

All repos for ubuntu jammy / raspbian bullseye mirror perfectly for amd64 / armhf / arm64

Only docker / jammy for armhf and arm64 fail

Hopefully you can solve that ?

=================================================================================
Details :

Sites look the same to me. e.g.
https://download.docker.com/linux/ubuntu/dists/jammy/stable/binary-armhf/
https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-armhf/

Could not quickly find a version number in the script, I think that would help.
I am using the version I downloaded  2022-07-27

Errors:
Only thing that looks strange is the double // in ubuntu//dists, see error lines below, no idea why it is there or if that is normal

=================================================================================
armhf

deb-armhf https://download.docker.com/linux/raspbian/ buster stable
ok

deb-armhf https://download.docker.com/linux/raspbian/ bullseye stable
ok

deb-armhf http://download.docker.com/linux/ubuntu focal stable
ok

deb-armhf http://download.docker.com/linux/ubuntu jammy stable
apt-mirror: can't open index download.docker.com/linux/ubuntu//dists/jammy/stable/binary-armhf/Packages in process_index at /usr/bin/apt-mirror line 932.

=================================================================================
arm64

deb-arm64 https://download.docker.com/linux/ubuntu focal stable
OK 

deb-arm64 https://download.docker.com/linux/ubuntu jammy stable
apt-mirror: can't open index download.docker.com/linux/ubuntu//dists/jammy/stable/binary-arm64/Packages in process_index at /usr/bin/apt-mirror line 932.

=================================================================================

**Comment by Roger53** [comment]
Thanks a lot for your feedback chutzimir, appreciated.

I did a Notepad compare, and I was and I am using the latest version of the apt-mirror from stifler

Then I tried a stripped list with only docker.com and then my full mirror.list in a virtual Ubuntu Desktop 20.04
    ( and aborted after PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP )
        Both works indeed, no errors

I am running the apt-mirror in a Ubuntu 22.04 docker container, all updates installed.
While running my apt-mirror docker container, so while a full apt-mirror update was running, I did exec into it and manually download the package files with wget, no problem

Strange

So it is more likely that it is something with my container then ?

So I will do some update and more testing 

Thanks

**Comment by Roger53** [comment]
Ended up to be a certificate problem inside the container
In the manual test I kind of instinctively used wget ... --no-check-certificate
Should have triggered me, but I got confused because I did NOT get an error for amd64, but it turned out that the amd64 repo was NOT updated also, but no error messages at all

Apparently a wget of a Packages file can fail, and no error message about that ?
Perhaps an improvement tip : better checks/error messages  by apt-mirror ?

installed ca-certificates in the container, solved

I will close the issue in a few days

**Comment by Stifler6996** [comment]
@Roger53 Sorry for my delayed response to this, but I'm glad to see that you have resolved the issue.

I can also comment that the double slashes in the url, will not cause an issue (its just that you have a trailing slash in the deb line repo). The program sanitises that before processing.

**Comment by chutzimir** [comment]
Close the issue?
