### ISSUE TITLE
Fork behind upstream?

### ISSUE THREAD

**Issue by kfiresmith** [Stifler6996/apt-mirror#46]
Hi Folks,
I'm just a user and not a developer by any means, so I may be getting this wrong, but it sort of seems like this fork is now actually behind some recent work on the upstream project.

A couple years ago I started using this fork because the upstream appeared to be abandoned and IIRC some compression scheme had changed in how repodata was compressed - but it now looks like there is some maintenance happening upstream.  

If that's correct and I'm not mixed up, would it be possible to get this fork rebased to pull in any upstream enhancements or fixes?  

Or since the original maintainer is still looking for maintainers and there is active work happening, maybe this fork could merge back with upstream and bring over whatever fixes or enhancements are present on the fork and maintenance could once again happen all on the same project?

Thanks, and apologies again if I've gotten any of this wrong.

**Comment by chutzimir** [comment]
You are right that this fork has been more responsive as apt-mirror was broken and there were no responses upstream. After a burst of activity upstream, all critical issues got fixed. There was even a plan to release a version last summer, but the activity died again.

Having said that, upstream has all the critical issues fixed, so it is safe to use either branch. The only fixes that are not upstream from this branch are:
- 44d92302fdfc606010ba1a5595a08522631a1c65 - no PR open upstream
- https://github.com/apt-mirror/apt-mirror/pull/163 - it's a feature, not a bugfix.

At this point I can recommend using the upstream as it also has some extra fixes that went it. I have been basing my own fork at https://github.com/chutzimir/apt-mirror/tree/dev on the upstream, with a few open PRs merged into the `dev` branch and it is what I use daily. It is basically upstream with 5 PRs merged in:
- apt-mirror/apt-mirror#143
- apt-mirror/apt-mirror#177
- apt-mirror/apt-mirror#178
- apt-mirror/apt-mirror#179
- chutzimir/apt-mirror#1

**Comment by Stifler6996** [comment]
I'm not sure if I could even rebase it tbh. I took a look at it a while ago when upstream got some activity, and it looked like it would be a nightmare to do. I did this in my spare time and while I code, I am not a professional coder.

Anyway looks like either will work for you.
