### ISSUE TITLE
How to fix "Permission denied" when I run `apt-mirror`

### ISSUE THREAD

**Issue by vp0122** [Stifler6996/apt-mirror#48]
![image](https://github.com/Stifler6996/apt-mirror/assets/117609511/48489a43-096a-48fb-8239-f11451af1f36)
After cloning this repo I replaced `/usr/bin/apt-mirror` with the cloned repo
and changed the permission using this command
`sudo chown root:root /usr/bin/apt-mirror && sudo chmod 755 /usr/bin/apt-mirror`
But as you can see in the screenshot, I am getting a `permission denied` error.
Please help me to fix it.
Thanks.

**Comment by vp0122** [comment]
![image](https://github.com/Stifler6996/apt-mirror/assets/117609511/9dc47653-3573-41ed-8a6a-4e6f9b4980ea)
This is my `mirror.list`

**Comment by rbh-se** [comment]
You must change permission for /usr/bin/apt-mirror. Give user apt-mirror right to execute:
**$ sudo chown apt-mirror:apt-mirror /usr/bin/apt-mirror**

**Comment by rbh-se** [comment]
You have set ownership of /var/spool/apt-mirror, to apt-mirror:apt-mirror?

You wrote; "After cloning this repo I replaced it with /usr/bin/apt-mirror". You mean you cloned the github repo to your harddisk and then copying  apt-mirror from the repo,  replasing /usr/bin/apt-mirror?

**Comment by vp0122** [comment]
@rbh-se yes

**Comment by vp0122** [comment]
I cloned the repo and replaced it with `/usr/bin/apt-mirror`

**Comment by vp0122** [comment]
Sorry. I replaced `/usr/bin/apt-mirror` with the cloned repo.
Could you share the command to change permission?

**Comment by vp0122** [comment]
> Do you have working /usr/bin/perl ?

I didn't check it yet. Let me check it. @zgrmrts

**Comment by vp0122** [comment]
![image](https://github.com/Stifler6996/apt-mirror/assets/117609511/e2732a9c-2747-495b-bf61-0235a657f10d)
I think I have a working version of Perl

**Comment by zgrmrts** [comment]
Can you check the execute rights with: `ls -l $(which apt-mirror)`

**Comment by vp0122** [comment]
@zgrmrts 
![image](https://github.com/Stifler6996/apt-mirror/assets/117609511/ba9bf47a-7894-4ddf-896c-ee539ca5c566)

**Comment by rbh-se** [comment]
> Could you share the command to change permission?

from "man chown"

    chown - change file owner and group
           -c, --changes
              like verbose but report only when a change is made
           -R, --recursive
              operate on files and directories recursively


So, run:

$ sudo chown -R -c apt:mirror:mirror /var/spool/apt-mirror

If no changes is reported, permisions was ok.

**Comment by vp0122** [comment]
@rbh-se I just ran it and no changes reported
![image](https://github.com/Stifler6996/apt-mirror/assets/117609511/ff329f16-3602-4ffd-b081-19387ed0597e)

**Comment by Stifler6996** [comment]
closing, no response.
