### ISSUE TITLE
 can't open index

### ISSUE THREAD

**Issue by mvitsvk** [Stifler6996/apt-mirror#49]
I ran into a problem `apt-mirror: can't open index apt.tn.ixsystems.com/apt-direct/bluefin/nightlies/nodejs//dists/bullseye/main/binary-i386/Packages in process_index at /usr/bin/apt-mirror line 934`
using pseudolegging, I found out that the `index` variable already has a slash.
```
!!! path=apt.tn.ixsystems.com/apt-direct/bluefin/nightlies/nodejs
!!! mirror=/mnt/pool/apt/mirror/apt.tn.ixsystems.com/apt-direct/bluefin/nightlies/nodejs
!!! index=/dists/bullseye/main/binary-all/Packages
```
I slightly changed the code in line 908 by adding a filter to remove the slash at the beginning of the line. The error disappeared.
` $index =~s/^\///;`

**Comment by Stifler6996** [comment]
Thanks, I'll have a look. However, in your mirror.list file, none of the paths should have a trailing /.

Can you check yours and see if you accidentally have a trailing slash in any of these:
```
set base_path         /var/spool/apt-mirror
set mirror_path       $base_path/mirror
set skel_path         $base_path/skel
set var_path          $base_path/var
```

**Comment by Stifler6996** [comment]
closing, no response.
