### ISSUE TITLE
Double slashes?

### ISSUE THREAD

**Issue by SamWang8891TW** [Stifler6996/apt-mirror#50]
Error:
"apt-mirror: can't open index mirror01.idc.hinet.net/ubuntu//dists/jammy-backports/universe/binary-amd64/Packages in process_index at /usr/bin/apt-mirror line 932.
]"

This is one of the many errors, but they look alike, so I just post one of them.

My guess is that there are double slashes for the url somewhere in the program.

**Comment by SamWang8891TW** [comment]
Version 0.5.4

**Comment by Stifler6996** [comment]
Those URLs are sanitised (after printing, so its confusing) the double slash does not affect its operation. (Its because you have not laid out your config cleanly, but it doesn't matter, See #49 )

Its likely the problem is the repo, but I'll need more info.

**Comment by SamWang8891TW** [comment]
K. I'll check my repo and post the config once I fixed my server. I can't access my server rn.

Thanks and have a nice day.

**Comment by SamWang8891TW** [comment]
Thanks for waiting and I'm sorry to tell u that I just abandoned my repo server due to some reasons. So I won't check where the problem is and

**Comment by SamWang8891TW** [comment]
Thanks for waiting and I'm sorry to tell u that I just abandoned my repo server due to some reasons. So I won't check where the problem is and I'll close the issue.

Maybe I'll setup a repo server again in the future, but at least not in the near future.

Thank u and have a great day.
