### ISSUE TITLE
Your tool does not like spaces

### ISSUE THREAD

**Issue by Roger53** [Stifler6996/apt-mirror#8]
Hi guys, great that you made this updated version, and I think it can be improved

I just lost 1TB of mirror data ( not only Ubuntu for amd64 ), when replaced the original apt-mirror Ubuntu 20.04 with your version ( no hard feelings, its not unique data, just takes some waiting time  :-)

Same issue as #5 

Using just 1 line as test :
deb http://archive.ubuntu.com/ubuntu                focal main restricted universe multiverse
leads to :
Failed to open Release file from http://archive.ubuntu.com/ubuntu/dists/Release at /usr/bin/apt-mirror line 522.

Details
I used a nice layout in the list file to keep the overview :

deb-amd64 http://archive.ubuntu.com/ubuntu         focal                  main universe
deb-amd64 http://archive.ubuntu.com/ubuntu         focal-security    main universe
deb-amd64 http://archive.ubuntu.com/ubuntu         focal-updates    main universe

deb-i386 http://archive.ubuntu.com/ubuntu             focal                  main universe
deb-i386 http://archive.ubuntu.com/ubuntu             focal-security    main universe
deb-i386 http://archive.ubuntu.com/ubuntu             focal-updates    main universe

Your tool does not accept the many spaces, and then does a cleanup, effectively deleting all existing data from my disk, so not really an 1:1 replacement  of the original (yet)

When I use 
deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse

it does work perfectly for one machine I tested

So perhaps you can change the tool to accept many spaces in the list lines ?
Or add a warning on the front page ?

did not yet test amd64/i386 to limit the size, as I think I now have all architectures, right ?

Thanks, keep up the good work :+1:

**Comment by Stifler6996** [comment]
I don't understand what you mean by spaces? Mine is set up exactly like this.

This is a snippet of one section of my config (The Ubuntu section, amd64 and arm64)

`
#### Official releases of Ubuntu
### Ubuntu Main (amd64, i386)

## Installer repositories (amd64) (Netboot) #If you want to boot from ipxe or tftp etc, you need these areas.
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic           main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic-security  main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
deb-amd64 http://archive.ubuntu.com/ubuntu focal            main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
#deb-amd64 http://archive.ubuntu.com/ubuntu focal-security   main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
deb-amd64 http://archive.ubuntu.com/ubuntu hirsute            main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
#deb-amd64 http://archive.ubuntu.com/ubuntu hirsute-security   main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer

## Regular repositories (amd64)
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic           main restricted universe multiverse
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic-security  main restricted universe multiverse
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic-updates   main restricted universe multiverse
#deb-amd64 http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse

deb-amd64 http://archive.ubuntu.com/ubuntu focal            main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu focal-security   main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu focal-updates    main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu focal-backports  main restricted universe multiverse

deb-amd64 http://archive.ubuntu.com/ubuntu hirsute            main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu hirsute-security   main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu hirsute-updates    main restricted universe multiverse
deb-amd64 http://archive.ubuntu.com/ubuntu hirsute-backports  main restricted universe multiverse

## Regular source repositories (amd64) NOTE: There is an issue with this currently. If the src repository doesn't contain the old Hash it will fail (most only have SHA1 these days)
#deb-src http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu bionic-proposed main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse

### Ubuntu Ports (arm64 etc)

## Installer repositories (arm64) (Netboot)
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic           main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic-security  main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal            main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal-security   main/debian-installer restricted/debian-installer universe/debian-installer multiverse/debian-installer

## Regular Port repositories (arm64)
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic           main restricted universe multiverse
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic-security  main restricted universe multiverse
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic-updates   main restricted universe multiverse
#deb-arm64 http://ports.ubuntu.com/ubuntu-ports bionic-backports main restricted universe multiverse

deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal            main restricted universe multiverse
deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal-security   main restricted universe multiverse
deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal-updates    main restricted universe multiverse
deb-arm64 http://ports.ubuntu.com/ubuntu-ports focal-backports  main restricted universe multiverse

## Tidy up
clean http://archive.ubuntu.com/ubuntu
clean http://ports.ubuntu.com/ubuntu-ports

#### End of Ubuntu repository Section
`

**Comment by Stifler6996** [comment]
Ill assume this has been resolved, and close. Mainly because I have made no changes whatsoever to how the config files is handled, compared to the original. So I can only assume there was some other issue, unrelated.
